name: Deploy ALL Package With Branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: |
             npm install
             npm run build
      - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@4.2.1
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: dist # The folder the action should deploy.
            ssh-key: ${{ secrets.DEPLOY_KEY }}